# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Zeepy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zeepy
  # add the Firebase pod for Google Analytics
  inhibit_all_warnings!
  pod 'RxSwift', '5.1.2'
  pod 'RxCocoa', '5.1.1'
  pod 'Moya', '~> 14.0'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'RangeSeekSlider'
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'RxKakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'RxKakaoSDKAuth'  # 카카오 로그인
  pod 'RxKakaoSDKUser'  # 사용자 관리

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'ZeepyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZeepyUITests' do
    # Pods for testing
  end

  post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

end
