# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zeepy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zeepy
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'PopupDialog', '~> 1.1'
  pod 'RxCocoa', '6.1.0'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'ZeepyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZeepyUITests' do
    # Pods for testing
  end

end
